spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: siuki
    password: Ssw0304!
    url: jdbc:mysql://localhost:3306/security20230725
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
